#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libdwarf
Version  : 20150115
Release  : 7
URL      : http://www.prevanders.net/libdwarf-20150115.tar.gz
Source0  : http://www.prevanders.net/libdwarf-20150115.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 LGPL-2.1
BuildRequires : elfutils-dev

%description
To just build libdwarf and dwarfdump one might do:
./configure
make dd
#You may need to be root to do the following copy commands
cp dwarfdump/dwarfdump      /usr/local/bin
cp dwarfdump/dwarfdump.conf /usr/local/lib
#The following is optional, not needed to run dwarfdump
#when doing the default build.
cp libdwarf/libdwarf.a      /usr/local/lib

%package dev
Summary: dev components for the libdwarf package.
Group: Development
Provides: libdwarf-devel

%description dev
dev components for the libdwarf package.


%prep
%setup -q -n dwarf-20150115

%build
%configure --disable-static --enable-shared
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install
## make_install_append content
mkdir -p %{buildroot}/usr/lib64
mkdir -p %{buildroot}/usr/include/libdwarf
cp libdwarf/*.h %{buildroot}/usr/include/libdwarf
cp libdwarf/*.so %{buildroot}/usr/lib64/
## make_install_append end

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libdwarf/common.h
/usr/include/libdwarf/config.h
/usr/include/libdwarf/dwarf.h
/usr/include/libdwarf/dwarf_abbrev.h
/usr/include/libdwarf/dwarf_alloc.h
/usr/include/libdwarf/dwarf_arange.h
/usr/include/libdwarf/dwarf_base_types.h
/usr/include/libdwarf/dwarf_die_deliv.h
/usr/include/libdwarf/dwarf_elf_access.h
/usr/include/libdwarf/dwarf_error.h
/usr/include/libdwarf/dwarf_frame.h
/usr/include/libdwarf/dwarf_funcs.h
/usr/include/libdwarf/dwarf_gdbindex.h
/usr/include/libdwarf/dwarf_global.h
/usr/include/libdwarf/dwarf_harmless.h
/usr/include/libdwarf/dwarf_incl.h
/usr/include/libdwarf/dwarf_line.h
/usr/include/libdwarf/dwarf_loc.h
/usr/include/libdwarf/dwarf_macro.h
/usr/include/libdwarf/dwarf_names.h
/usr/include/libdwarf/dwarf_names_enum.h
/usr/include/libdwarf/dwarf_names_new.h
/usr/include/libdwarf/dwarf_opaque.h
/usr/include/libdwarf/dwarf_reloc_arm.h
/usr/include/libdwarf/dwarf_reloc_mips.h
/usr/include/libdwarf/dwarf_reloc_ppc.h
/usr/include/libdwarf/dwarf_reloc_ppc64.h
/usr/include/libdwarf/dwarf_reloc_x86_64.h
/usr/include/libdwarf/dwarf_tsearch.h
/usr/include/libdwarf/dwarf_types.h
/usr/include/libdwarf/dwarf_util.h
/usr/include/libdwarf/dwarf_vars.h
/usr/include/libdwarf/dwarf_weaks.h
/usr/include/libdwarf/dwarf_xu_index.h
/usr/include/libdwarf/libdwarf.h
/usr/include/libdwarf/libdwarfdefs.h
/usr/include/libdwarf/malloc_check.h
/usr/include/libdwarf/pro_alloc.h
/usr/include/libdwarf/pro_arange.h
/usr/include/libdwarf/pro_die.h
/usr/include/libdwarf/pro_encode_nm.h
/usr/include/libdwarf/pro_error.h
/usr/include/libdwarf/pro_expr.h
/usr/include/libdwarf/pro_frame.h
/usr/include/libdwarf/pro_incl.h
/usr/include/libdwarf/pro_line.h
/usr/include/libdwarf/pro_macinfo.h
/usr/include/libdwarf/pro_opaque.h
/usr/include/libdwarf/pro_reloc.h
/usr/include/libdwarf/pro_reloc_stream.h
/usr/include/libdwarf/pro_reloc_symbolic.h
/usr/include/libdwarf/pro_section.h
/usr/include/libdwarf/pro_types.h
/usr/include/libdwarf/pro_util.h
/usr/lib64/*.so
